// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://neondb_owner:npg_cCWo2bVGRt5s@ep-gentle-sound-axyewasy-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require",
  },
});
